services:
  - type: web
    name: laborlink-api
    env: node
    plan: free
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 1d
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: LaborLink
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
